name: test_alert_current_wait

on:
  workflow_run:
    workflows: ["mock-workflow"]
    types: 
      - completed

jobs:

  alert_current_pr:
    env: # Or as an environment variable
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    runs-on: ubuntu-latest
    name: Alert Current in Queue after wait
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Alert queue after wait
        uses: ./ # Uses an action in the root directory
        id: alert
        with:
          mode: 'ALERT'
          alert_message: ${{ github.event.workflow.name }} is complete. Time to merge after a wait!
          channel: 'merge-queue'
      # Use the output from the `alert` step
      - name: Get the output status
        run: echo "status => ${{ steps.alert.outputs.status }}"